version: "3.7"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: fantastest
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
